export const SUPABASE_URL = "https://erieaeemvxwsqgaqadrc.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyaWVhZWVtdnh3c3FnYXFhZHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg4NTczNTQsImV4cCI6MjA0NDQzMzM1NH0.j_rex18MOV8CASYW1j2sNZ9gVBwXcncLwBr3w7kRLJE";
